"""
Django settings for detmir project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&q+1+2qpxp)n@9h_ppvsgbq143i8v7t@uhgfxiyxpuj(o#2)z5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Mir', #добавили наше приложение
    'rest_framework', #компонент для построения веб-сервисов api
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'detmir.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', #добавили
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'detmir.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru' #сменили язык

TIME_ZONE = 'Europe/Minsk' #сменили время

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' #добавили

LOGIN_URL = '/admin/login/'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #задаем вывод отправляемых писем напрямую в консоль терминала
EMAIL_HOST = 'localhost' #указываем имя локального хоста для почтового сервера
EMAIL_PORT = 25 #задаем стандартный порт для работы локальной почтовой службы
EMAIL_HOST_USER = '' #оставляем пустым имя пользователя для локального тестирования
EMAIL_HOST_PASSWORD = '' #оставляем пустым пароль пользователя для локального тестирования
EMAIL_USE_TLS = False #отключаем обязательное шифрование для локального вывода писем

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', #разрешаем доступ к интерфейсу api только авторизованным пользователям
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', #подключаем стандартную проверку сессии пользователя браузера
        'rest_framework.authentication.BasicAuthentication', #подключаем базовую проверку подлинности для технических запросов
    ],
}

STATIC_URL = '/static/' # url префикс для доступа к статическим файлам
STATICFILES_DIRS = [BASE_DIR / 'static'] # технический указатель на папку со стилями проекта
STATIC_ROOT = BASE_DIR / 'staticfiles' # директория автоматического сбора статики при деплое
MEDIA_URL = '/media/' # url префикс для загружаемых картинок детских товаров
MEDIA_ROOT = BASE_DIR / 'media' # корневая директория для хранения изображений игрушек на диске